#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi rofi-prompt

power_off='  shutdown'
reboot='  reboot'
lock='  lock'
suspend='鈴  suspend'
log_out='  logout'

chosen=$(printf '%s;%s;%s;%s;%s\n' "$power_off" "$reboot" "$lock" "$suspend" \
                                   "$log_out" \
    | rofi -config ~/.config/rofi/powermenu.rasi \
           -dmenu \
           -sep ';' \
           -selected-row 2 \
           -p power)

case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        # TODO Add your lockscreen command.
        $HOME/.config/i3/scripts/blur-lock
        ;;

    "$suspend")
        # Pause music and mute volume before suspending.
        mpc --quiet pause
        amixer set Master mute
        # TODO Add your suspend command.
        hibernate
        ;;

    "$log_out")
        # TODO Add your log out command.
        bspc quit
        ;;

    *) exit 1 ;;
esac
