#!/bin/sh

screens=$($HOME/.config/scripts/numscreens.py)

# desktop screens
$HOME/.screenlayout/layout.sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

if [ $screens -eq 2 ] 
then
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8 9 0
    echo "2 monitors"
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
    echp "one or more monitors"
fi

bspc config border_width         2
bspc config focused_border_color \#91d7e3
bspc config normal_border_color  \#f0c6c6
bspc config active_border_color  \#f0c6c6
bspc config border_radius        12
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a konsole desktop='^1' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a discord desktop='^6' follow=on
bpsc rule -a spotify desktop='^9' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spectacle state=floating

# polybar
$HOME/.config/polybar/launch.sh

nm-applet &
nitrogen --restore
dunst &
picom --config $HOME/.config/picom/picom.conf &
discord &
premid &
emancs --daemon
